title: Risk IT&#58 The Future of Risk Work
description: Understanding the Present and Designing the Future of Data-Intensive ‘Risk Work’ in Emergency Services

theme: minima



# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/partners.md
  - _pages/authors.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
